name: "Waveshare PoE HAT (B)"
description: "PoE HAT Support"
version: "1.0.3"
slug: "poe_hat"
init: false
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
devices:
  - /dev/i2c-0
  - /dev/i2c-1
  - /dev/i2c-10
  - /dev/i2c-22
options:
  fan_temp: 46
  #delta_temp: 5
  #sleep_duration: 30
schema:
  fan_temp: int
  #delta_temp: int
  #sleep_duration: int
